(define re
  '(seq (atom 0)
        (disj (atom 1)
              (atom 2))
        (seq (disj (atom 3)
                   (atom 4))
             (atom 5))))

(define test_re
  (lambda (candidate)
    (and
     (candidate '(0 1 3 5))
     (candidate '(0 1 4 5))
     (candidate '(0 2 3 5))
     (candidate '(0 2 3 5))
     (not (candidate '(0 0 3 5)))
     (not (candidate '(0 0 4 5)))
     (not (candidate '(0 1 5 5)))
     (not (candidate '(0 2 5 5)))
     (not (candidate '(0 1 5)))
     (not (candidate '(0 2 5)))
     (not (candidate '(0 3 5)))
     (not (candidate '(0 4 5)))
     )))

(define c_re
  (lambda (ns)
    (and ;(printf "ns1: ~s~n" ns)
         (pair? ns)
         (= (car ns) 0)
         (let* ([ns (cdr ns)]
                [n (car ns)])
           (and ;(printf "n ns2: ~s ~s~n" n ns)
                (or (= n 1)
                    (= n 2))
                (pair? ns)
                (let* ([ns (cdr ns)]
                       [n (car ns)])
                  (and ;(printf "n ns3: ~s ~s~n" n ns)
                       (or (= n 3)
                           (= n 4))
                       (pair? ns)
                       (let ([ns (cdr ns)])
                         (and (= (car ns) 5)
                              (null? (cdr ns)))))))))))

(define c_re2
  (lambda (ns)
    (and (pair? ns)
         (let ([n (car ns)]
               [ns (cdr ns)])
           (and (= n 0)
                (pair? ns)
                (let ([n (car ns)]
                      [ns (cdr ns)])
                  (and (or (= n 1)
                           (= n 2))
                       (pair? ns)
                       (let ([n (car ns)]
                             [ns (cdr ns)])
                         (and ;(printf "n ns3: ~s ~s~n" n ns)
                          (or (= n 3)
                              (= n 4))
                          (pair? ns)
                          (let ([n (car ns)]
                                [ns (cdr ns)])
                            (and (= n 5)
                                 (null? ns))))))))))))

(define c_re3
  (lambda (ns1)
    (and (pair? ns1)
         (let ([n2 (car ns1)]
               [ns2 (cdr ns1)])
           (and (= n2 0)
                (pair? ns2)
                (let ([n3 (car ns2)]
                      [ns3 (cdr ns2)])
                  (and (or (= n3 1)
                           (= n3 2))
                       (pair? ns3)
                       (let ([n4 (car ns3)]
                             [ns4 (cdr ns3)])
                         (and ;(printf "n ns3: ~s ~s~n" n ns)
                          (or (= n4 3)
                              (= n4 4))
                          (pair? ns4)
                          (let ([n5 (car ns4)]
                                [ns5 (cdr ns4)])
                            (and (= n5 5)
                                 (null? ns5))))))))))))

(define c_re4
  (lambda (ns1)
    (and (pair? ns1)
         (let (;[n2 (car ns1)]
               [ns2 (cdr ns1)])
           (and (= (car ns1) 0)
                (pair? ns2)
                (let ([n3 (car ns2)]
                      [ns3 (cdr ns2)])
                  (and (or (= n3 1)
                           (= n3 2))
                       (pair? ns3)
                       (let ([n4 (car ns3)]
                             [ns4 (cdr ns3)])
                         (and ;(printf "n ns3: ~s ~s~n" n ns)
                          (or (= n4 3)
                              (= n4 4))
                          (pair? ns4)
                          (let (;[n5 (car ns4)]
                                        ;[ns5 (cdr ns4)]
                                )
                            (and (= (car ns4) 5)
                                 (null? (cdr ns4)))))))))))))

(define c_re5
  (lambda (ns0)
    (if (pair? ns0)
        (if (= (car ns0) 0)
            (let ([ns1 (cdr ns0)])
              (let ([k1 (lambda (ns2)
                          (let ([k2 (lambda (ns3)
                                      (if (pair? ns3)
                                          (if (= (car ns3) 5)
                                              (let ([ns4 (cdr ns3)])
                                                (null? ns4))
                                              #f)
                                          #f))])
                            (or (if (pair? ns2)
                                    (if (= (car ns2) 3)
                                        (let ([ns3 (cdr ns2)])
                                          (k2 ns3))
                                        #f)
                                    #f)
                                (if (pair? ns2)
                                    (if (= (car ns2) 4)
                                        (let ([ns3 (cdr ns2)])
                                          (k2 ns3))
                                        #f)
                                    #f))))])
                (or (if (pair? ns1)
                        (if (= (car ns1) 1)
                            (let ([ns2 (cdr ns1)])
                              (k1 ns2))
                            #f)
                        #f)
                    (if (pair? ns1)
                        (if (= (car ns1) 2)
                            (let ([ns2 (cdr ns1)])
                              (k1 ns2))
                            #f)
                        #f))))
            #f)
        #f)))


(define test_count_re
  (lambda (candidate)
    (and
     (= (candidate '(0 1 3 5)) 1)
     (= (candidate '(0 1 4 5)) 1)
     (= (candidate '(0 2 3 5)) 1)
     (= (candidate '(0 2 3 5)) 1)
     (= 0 (candidate '(0 0 3 5)))
     (= 0 (candidate '(0 0 4 5)))
     (= 0 (candidate '(0 1 5 5)))
     (= 0 (candidate '(0 2 5 5)))
     (= 0 (candidate '(0 1 5)))
     (= 0 (candidate '(0 2 5)))
     (= 0 (candidate '(0 3 5)))
     (= 0 (candidate '(0 4 5)))
     )))

(define count_re
  (lambda (ns0)
    (if (pair? ns0)
        (if (= (car ns0) 0)
            (let ([ns1 (cdr ns0)])
              (let ([k1 (lambda (ns2)
                          (let ([k2 (lambda (ns3)
                                      (if (pair? ns3)
                                          (if (= (car ns3) 5)
                                              (let ([ns4 (cdr ns3)])
                                                (if (null? ns4)
                                                    1
                                                    0))
                                              0)
                                          0))])
                            (+ (if (pair? ns2)
                                    (if (= (car ns2) 3)
                                        (let ([ns3 (cdr ns2)])
                                          (k2 ns3))
                                        0)
                                    0)
                               (if (pair? ns2)
                                   (if (= (car ns2) 4)
                                       (let ([ns3 (cdr ns2)])
                                         (k2 ns3))
                                       0)
                                   0))))])
                (+ (if (pair? ns1)
                       (if (= (car ns1) 1)
                           (let ([ns2 (cdr ns1)])
                             (k1 ns2))
                           0)
                       0)
                   (if (pair? ns1)
                       (if (= (car ns1) 2)
                           (let ([ns2 (cdr ns1)])
                             (k1 ns2))
                           0)
                       0))))
            0)
        0)))

(unless (test_re c_re)
  (printf "test failed~n"))
(unless (test_re c_re2)
  (printf "test failed~n"))
(unless (test_re c_re3)
  (printf "test failed~n"))
(unless (test_re c_re4)
  (printf "test failed~n"))
(unless (test_re c_re5)
  (printf "test5 failed~n"))
(unless (test_count_re count_re)
  (printf "test6 failed~n"))
